name: "[gradle-plugin] release"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to release the gradle-plugin from"
        required: true
        default: "main"

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Verify that branch matches pattern release/*
        run: |
          if [[ "${{ github.event.inputs.branch }}" != release/* ]]; then
            echo "Error: This workflow must be triggered from a branch matching 'release/*'."
            exit 1
          fi

      - name: Verify user triggering the workflow
        id: verify-user
        run: |
          # Get the triggering user from the environment
          TRIGGERING_USER=${{ github.actor }}
          
          # Read the CODEOWNERS file and check if the user is listed
          if ! grep -Fxq "@$TRIGGERING_USER" CODEOWNERS; then
            echo "Error: User $TRIGGERING_USER is not authorized to trigger the workflow."
            exit 1
          else
            echo "User $TRIGGERING_USER is valid."
          fi

  release:
    name: Release
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: gradle

      - name: Publish release
        run: ./gradlew publishPlugins
        working-directory: ./plugins/gradle
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}