name: Javalin DI - CI

on:
  pull_request:
    branches:
      - main
      - develop
      - '**' # Run on any branch with a PR

jobs:
  javalin-di-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Run tests
        run: ./javalin-di/gradlew check

      - name: Run E2E tests
        run: ./javalin-di/gradlew e2eTest

