name: "[library] update build status"

on:
  push:
    branches:
      - main

jobs:
  update-build-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: gradle

      - name: Run tests
        run: ./gradlew check
        working-directory: ./library

      - name: Run E2E tests
        run: ./gradlew e2eTest
        working-directory: ./library

      - name: Run test coverage
        run: ./gradlew testCoverage
        working-directory: ./library

      - name: Update build badge data with failure status
        if: failure()
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.BOT_TOKEN_UPDATE_BADGE }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/gists/896b6842fd99039b5a14141bd2e80f41 \
            -d '{
              "files": {
                "build.json": {
                  "content": "{ \"schemaVersion\": 1, \"label\": \"build\", \"message\": \"failed\", \"color\": \"d94136\" }"
                }
              }
            }'

      - name: Update build badge data with success status
        if: success()
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.BOT_TOKEN_UPDATE_BADGE }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/gists/896b6842fd99039b5a14141bd2e80f41 \
            -d '{
              "files": {
                "build.json": {
                  "content": "{ \"schemaVersion\": 1, \"label\": \"build\", \"message\": \"passing\", \"color\": \"2aa353\" }"
                }
              }
            }'

      - name: Update code coverage badge
        if: success()
        working-directory: ./library
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.BOT_TOKEN_UPDATE_BADGE }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/gists/896b6842fd99039b5a14141bd2e80f41 \
            -d "$(jq -n --arg message "$(cat build/coverage.txt)" \
            '{
            files: {
              "code-coverage.json": {
                content: {
                  "schemaVersion": 1,
                  "label": "code coverage",
                  "message": $message,
                  "color": "2aa353"
                }
              }
            }
          }')"